### ISSUE TITLE
Takes 10 seconds  to load left panel..?

### ISSUE THREAD

**Issue by anguila** [rvspt/QuickAdhoc-QS#3]
It takes about 10 seconds to just load the left panel.. so when you open the sheet feels like the extension is not working, and after a while it shows up.

Any idea how to fix this?

Davifd

**Comment by rvspt** [comment]
I've noticed it in apps that have an extent amount of Library items. Couldn't get some time to see what can be optimized to reduce this time. I am most certain that the getDimensionDetails(), getMeasures() and getSheetObjects() might need to be reviewd in order to do it in a quicker step.

Renato
