### ISSUE TITLE
how to selected one dimension and mesures defaults

### ISSUE THREAD

**Issue by panchaldixit** [rvspt/QuickAdhoc-QS#5]
whats changes i have to do for defaults one selection of dimension ??

**Comment by rvspt** [comment]
I'd possibly tackle this way:
1 - Modify the 'properties.js' file to take in account your desired Dimension(s) or Measure(s). Can be static or dynamic, depending if you want a simple text field to input the library ID of the dimension or measure or if you want a drop down with what is available.
2 - When loading the target object (table) info in the extension - at QuickAdhoc.js - add the logic to verify if the desired contents are already in the object or not and add them if required. You'd need to fiddle both with the renderExtension() and the paintOptions(). The first to check if you need to add and the second to add, if indeed needed.

I hope this made some kind of sense :)
