### ISSUE TITLE
Quick Ad-hoc

### ISSUE THREAD

**Issue by spavankumar1980** [rvspt/QuickAdhoc-QS#6]
Thanks for the nice extension.

I was using this extension and see some issue with formatting of the columns goes missing once hide and show (like background color,Number formatting) . 
![before](https://cloud.githubusercontent.com/assets/23215379/19931411/6cbd6eea-a0da-11e6-8c47-b265f44fa35f.png)
![sales removed](https://cloud.githubusercontent.com/assets/23215379/19931412/6cbdb7e2-a0da-11e6-9ca1-c329773ed190.png)
![sales column added again](https://cloud.githubusercontent.com/assets/23215379/19931413/6cbea30a-a0da-11e6-8a4b-9a28c17f8bb4.png)

**Comment by rvspt** [comment]
Hello spavankumar1980, the extension at this moment "destroys" and "creates" the columns. As it is not storing previous formats, it is indeed destroying and creating the contents ad-hoc. But you raise a nice point for improvement. I'll take note of it and if time allows, I'll add the feature.
