### ISSUE TITLE
Invalid sort order in properties

### ISSUE THREAD

**Issue by dustinbaxa** [rvspt/QuickAdhoc-QS#7]
Hi! First of all, I love the extension. Unfortunately, it is a little buggy at times. I am having an issue which is hard to replicate, but after selecting and deselecting a few dimensions/measures I get an error message that says "Invalid sort order in properties". When I go to the Sorting section in the properties panel, there are no dimensions in there. Even when I select another dimension or measure, the error doesnt go away nor does anything appear in the sorting. The only way to get rid of it is to build a new table and map the extension to it. I am using Sense Enterprise 3.1.1.

**Comment by rvspt** [comment]
Albeit being hard to replicate, could you (try to) send me a trimmed example and the sequence that got you in that buggy area? I'd like to look into it so I could squash this bug.
